# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseNew',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notices.Base')),
                ('description', models.CharField(max_length=200)),
            ],
            bases=('notices.base',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('basenew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notices.BaseNew')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            bases=('notices.basenew',),
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('basenew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notices.BaseNew')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('notices.basenew',),
        ),
    ]
