# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='pub_date',
        ),
    ]
