# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_base_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsItem',
            new_name='Notice',
        ),
    ]
